/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.nwfva.kupsimulator;

import de.nwfva.kupSIM.DataCompletion;
import de.nwfva.kupSIM.Growth;
import de.nwfva.kupSIM.StandGen;
import de.nwfva.kupSIM.Summary;
import de.nwfva.kupsimulator.config.SimulatorConfiguration;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import treegross.base.Stand;
import treegross.base.TreegrossXML2;

import javax.swing.*;
import java.io.File;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;

public class KupMainForm extends javax.swing.JFrame {

    private static final Logger logger = LogManager.getLogger(KupMainForm.class);

    Stand st = null;
    String localPath = "";
    OutputStream os = null;
    PrintWriter out = null;
    private JPanel panel1;

    private SimulatorConfiguration configuration;
    private DataCompletion dataCompletion;
    private Growth growth;
    private StandGen standGen;
    private Summary summary;


    /**
     * Creates new form KupMainForm
     */
    public KupMainForm() {
        initDependencies();
        initComponents();
        ensureOutputFolderIsAvailable();
        jLabel6.setText("");
        jLabel11.setText("");

    }

    private void initDependencies() {

        this.configuration = new SimulatorConfiguration();
        this.dataCompletion = new DataCompletion();
        this.growth = new Growth();
        this.standGen = initStandGen();
        this.summary = new Summary();
    }

    private StandGen initStandGen() {

        String outputDir = configuration.getConfiguration().getString("simulator.config.output.folder");
        String configDir = configuration.getConfiguration().getString("simulator.config.dir");
        String configFile = configuration.getConfiguration().getString("simulator.config.settings");
        String modelRegion = configuration.getConfiguration().getString("simulator.config.region");

        return new StandGen(outputDir, configDir, configFile, modelRegion, logger);
    }

    private void ensureOutputFolderIsAvailable() {

        String outputDir = configuration.getConfiguration().getString("simulator.config.output.folder");
        Path outputDirPath = Paths.get(outputDir);

        File file = outputDirPath.toFile();
        boolean createdDir = file.mkdirs();

        logger.info("Created output diretory {}", createdDir);
    }

    private String getOutputFile(String filename) {

        String outputDir = configuration.getConfiguration().getString("simulator.config.output.folder");
        Path outputDirPath = Paths.get(outputDir, filename);

        File file = outputDirPath.toFile();
        return file.getAbsolutePath();
    }


    private void startSimulation() {

        TreegrossXML2 xmlParser = new TreegrossXML2();

        String clone = (String) jComboBox1.getSelectedItem();
        double awc = Double.parseDouble(jTextField1.getText());
        int doyPlant = Integer.parseInt(jTextField2.getText());
        double prec = Double.parseDouble(jTextField3.getText());
        double temp = Double.parseDouble(jTextField4.getText());
        int bz = Integer.parseInt(jTextField5.getText());

        st = this.standGen.standGen(clone, awc, doyPlant, prec, temp, bz);
        this.dataCompletion.completeData(st);

        xmlParser.saveAsXML(st, getOutputFile("standYear1.xml"));

        // YEAR 2
        this.growth.grow(st);
        this.dataCompletion.completeData(st);

        xmlParser.saveAsXML(st, getOutputFile("standYear2.xml"));

        // YEAR 3
        this.growth.grow(st);
        this.dataCompletion.completeData(st);

        jLabel6.setText(summary.getSummaryString(st));


        xmlParser.saveAsXML(st, getOutputFile("standYear3.xml"));


        // Year 4 Resprout after harvest
        this.growth.resprout(st);

        // Data completion year 4
        this.dataCompletion.completeData(st);

        xmlParser.saveAsXML(st, getOutputFile("standYear4.xml"));


        // Year 5
        this.growth.grow(st);
        this.dataCompletion.completeData(st);


        xmlParser.saveAsXML(st, getOutputFile("standYear5.xml"));

        // Year 6
        this.growth.grow(st);
        this.dataCompletion.completeData(st);



        jLabel11.setText(summary.getSummaryString(st));


        xmlParser.saveAsXML(st, getOutputFile("standYear6.xml"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SRC Stand Simulator");
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Select clone and site conditions");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Start simulation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.GridLayout(3, 4));

        jLabel4.setText("Clone");
        jPanel4.add(jLabel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"MAX", "HYB",
                "AF2", "ING", "TOR"}));
        jPanel4.add(jComboBox1);

        jLabel7.setText("<html><body>Available water capacity in <br> 0 to 60 cm soil depth <br> (model range: 55 - 112)");
        jPanel4.add(jLabel7);

        jTextField1.setText("65.9");
        jPanel4.add(jTextField1);

        jLabel8.setText("<html><body>Julian day of planting <br> (model range: 115 - 140)</body></html>");
        jPanel4.add(jLabel8);

        jTextField2.setText("130");
        jPanel4.add(jTextField2);

        jLabel9.setText("<html><body>Sum of precipitation in May and June <br> " +
                "(model range: 110 - 183 mm)</body></html>");
        jPanel4.add(jLabel9);

        jTextField3.setText("130.3");
        jPanel4.add(jTextField3);

        jLabel10.setText("<html><body>Mean monthly temperature in June and July <br>" +
                " (model range: 16 - 19 °C)</body></html>");
        jPanel4.add(jLabel10);

        jTextField4.setText("16.6");
        jPanel4.add(jTextField4);

        jLabel12.setText("<html><body>German agricultural soil quality rating \"Bodenzahl\" <br>" +
                " (model range: 14 - 100)</body></html>");
        jPanel4.add(jLabel12);

        jTextField5.setText("34");
        jPanel4.add(jTextField5);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("After the first rotation");
        jPanel2.add(jLabel2, java.awt.BorderLayout.NORTH);

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(112, Short.MAX_VALUE)
                        )
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)
                                .addContainerGap(150, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("After the second rotation");
        jPanel3.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel11.setText("jLabel11");


        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                //jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                // .addGap(0, 1070, Short.MAX_VALUE)
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(112, Short.MAX_VALUE))


        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel11)
                                .addContainerGap(150, Short.MAX_VALUE))

                //.addGap(0, 190, Short.MAX_VALUE)


        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        setBounds(0, 0, 1080, 652);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Start simulation
        jLabel6.setText("Simulation started");

        startSimulation();
    }

    //GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KupMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KupMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KupMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KupMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KupMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
